# add ci-cd steps here
name: AIOps-DVC-NLP-project

on: [push] ## when it is triggered (wheteher any new update push)

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest] 
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: 'actions/setup-python@v2'
        with:
           python-version: '3.7'
      - name: cml-run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          ## Your ML Workflow Container
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro         
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          dvc metrics show >> report.md
          cml-send-comment report.md